"use client"

import { Button as ButtonPrimitive } from "@base-ui/react/button"
import { cva, type VariantProps } from "class-variance-authority"
import { clsx, type ClassValue } from "clsx"
import { motion, type Transition } from "motion/react"
import { twMerge } from "tailwind-merge"

/* Base UI primitive styled to shadcn conventions. Consumes only standard
   shadcn theme tokens — drops into any stock shadcn project unchanged.
   cn is inlined so the file is a single-copy port.

   ── DO NOT EDIT THIS FILE TO RESTYLE ──────────────────────────────────
   This file is a portable component copied across projects; it must stay
   identical everywhere. All restyling belongs in the project's theme:
   - Radius: `rounded-lg` resolves through --radius-lg → --radius in
     globals.css. To change corner radius, override --radius there
     (e.g. `--radius: 0.875rem;`). Never hardcode rounded-* values here.
   - Colors: override the standard shadcn token values (--primary,
     --secondary, --accent, --ring, ...) in globals.css. Never put hex
     values or new class names here.
   - Per-instance tweaks: use the props (variant/size/shape/press/hover)
     or the className prop at the call site — className wins via cn().
   Only edit this file to change the component's API for every project.
   ──────────────────────────────────────────────────────────────────────

   ── REPLACING AN OLDER COPY OF THIS FILE ──────────────────────────────
   Size names changed (2026-07). Update call sites when upgrading:
     sm → xs · default → small · lg → medium · xl → large
     icon-sm → icon-xs · icon → icon-small · icon-lg → icon-medium ·
     icon-xl → icon-large
   xs also shrank 28px → 24px (12px/500 label). The unspecified default
   size is now medium (36px; previously small/32px). Hover motion moved to
   one prop: elevate={true} → hover="elevate"; boolean grow → hover="grow".
   New dep: `motion` (press/hover physics). TypeScript flags every renamed
   call site.
   ──────────────────────────────────────────────────────────────────────

   Usage rules (for call sites, not this file):
   - Never set aria-label on a button with visible text — it overrides the
     label for screen readers. aria-label is for icon-only buttons, and
     should name action + target ("Copy deployment URL"), not the icon.
   - Disable a button only when the action is impossible. Prefer leaving
     it enabled and surfacing the error on click.

   Deps: @base-ui/react, class-variance-authority, clsx, tailwind-merge,
   motion. Motion drives scale/lift physics (spring, velocity-continuous
   interruption); colors stay CSS transitions. tailwind-merge is
   load-bearing — base sets border-transparent and rounded-lg; outline's
   border-border and capsule's rounded-full only win through cn(). */

function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

const MotionButton = motion.create(ButtonPrimitive)

const SPRING: Transition = { type: "spring", stiffness: 500, damping: 30, mass: 0.6 }

const ELEVATE_SHADOW =
  "0px 1px 6px rgba(0,0,0,0.04), 0px 0px 24px rgba(0,0,0,0.05)"
const ELEVATE_SHADOW_NONE =
  "0px 1px 6px rgba(0,0,0,0), 0px 0px 24px rgba(0,0,0,0)"

const buttonVariants = cva(
  "group/button inline-flex shrink-0 items-center justify-center cursor-pointer rounded-lg border border-transparent font-medium whitespace-nowrap transition-colors outline-none select-none focus-visible:ring-1 focus-visible:ring-[color:var(--focus-ring,#6B97FF)] focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        // hover: is gated on enabled: because disabled swaps pointer-events
        // suppression for a visible not-allowed cursor — without the gate,
        // disabled buttons would still paint hover feedback.
        default:
          "bg-primary text-primary-foreground enabled:hover:bg-primary/90 enabled:active:bg-primary/80",
        secondary:
          "bg-foreground/10 text-foreground enabled:hover:bg-foreground/15 enabled:active:bg-foreground/10 aria-expanded:bg-foreground/10",
        // Secondary/outline/ghost fills are foreground alpha washes, not
        // secondary/accent tokens: stock shadcn ships secondary = muted =
        // accent (a near-invisible wash), so token fills give no usable
        // rest color and identical hover→press steps on an unmodified
        // theme. Foreground-mix derives a monotonic ladder (5% hover wash,
        // 10% press/secondary rest, 15% secondary hover) that works in
        // both modes with zero token requirements.
        outline:
          "border-border bg-transparent enabled:hover:bg-foreground/5 enabled:active:bg-foreground/10 aria-expanded:bg-foreground/5",
        ghost:
          "text-muted-foreground bg-transparent enabled:hover:bg-foreground/5 enabled:hover:text-foreground enabled:active:bg-foreground/10 aria-expanded:bg-foreground/5 aria-expanded:text-foreground",
      },
      // Padding grows with size; icon side tightens when an icon is
      // present. Ladder: 24/32/36/40px heights, 12/14/14/16px labels,
      // 8/12/16/20px side padding.
      size: {
        xs: "h-6 gap-1 px-2 text-xs has-data-[icon=inline-end]:pr-1 has-data-[icon=inline-start]:pl-1 [&_svg:not([class*='size-'])]:size-3",
        small:
          "h-8 gap-1.5 px-3 text-sm has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2",
        medium:
          "h-9 gap-1.5 px-4 text-sm has-data-[icon=inline-end]:pr-2.5 has-data-[icon=inline-start]:pl-2.5",
        large:
          "h-10 gap-2 px-5 text-base has-data-[icon=inline-end]:pr-3.5 has-data-[icon=inline-start]:pl-3.5",
        "icon-xs": "size-6",
        "icon-small": "size-8",
        "icon-medium": "size-9",
        "icon-large": "size-10",
      },
      // Declared after size so tailwind-merge lets rounded-full win over the
      // base rounded-lg. rounded = uniform 8px; capsule = stadium (perfect
      // circle on icon sizes).
      shape: {
        rounded: "",
        capsule: "rounded-full",
      },
      // Motion (not CSS) drives the scale physics for press/hover — these
      // variant keys exist for compoundVariants and API typing.
      press: {
        none: "",
        shrink: "",
        bounce: "",
      },
      // One hover effect at a time by design: grow and elevate fight each
      // other visually, so they live on a single prop. grow pairs well
      // with press="bounce"; elevate reads best with press="none". grow is
      // intentionally inert on outline/ghost (transparent variants read
      // better still) — force it via the JS escape hatch if truly needed.
      hover: {
        none: "",
        grow: "",
        elevate: "",
      },
    },
    compoundVariants: [
      // At 24px tall the full --radius reads as a capsule; step rounded
      // xs down to --radius-md (radius − 2px) so corners stay corners.
      { size: "xs", shape: "rounded", className: "rounded-md" },
      { size: "icon-xs", shape: "rounded", className: "rounded-md" },
      // With scale press feedback, ghost keeps its hover wash while
      // pressed instead of stepping brighter — the scale is the feedback,
      // and a transparent variant flashing brighter mid-shrink reads as
      // text-only wobble. The brighter press wash only exists at
      // press="none", where color is the sole feedback channel.
      { press: "shrink", variant: "ghost", className: "enabled:active:bg-foreground/5" },
      { press: "bounce", variant: "ghost", className: "enabled:active:bg-foreground/5" },
    ],
    defaultVariants: {
      variant: "default",
      size: "medium",
      shape: "capsule",
      press: "none",
      hover: "none",
    },
  }
)

function Spinner() {
  return (
    <svg
      className="animate-spin"
      viewBox="0 0 24 24"
      fill="none"
      aria-hidden="true"
    >
      <circle
        cx="12"
        cy="12"
        r="10"
        stroke="currentColor"
        strokeWidth="3"
        className="opacity-25"
      />
      <path
        d="M12 2a10 10 0 0 1 10 10"
        stroke="currentColor"
        strokeWidth="3"
        strokeLinecap="round"
      />
    </svg>
  )
}

type StateColors = {
  foreground?: string
  background?: string
  border?: string
}

type CustomColors = {
  normal?: StateColors
  hover?: StateColors
  active?: StateColors
}

/* hover/active fall back to normal per-key, so a full `normal` plus one
   hover override is a valid spec. Values are any CSS color, including
   var(--token) references. */
const customClasses =
  "text-(--btn-fg,inherit) bg-(--btn-bg,transparent) border-(--btn-border,transparent) enabled:hover:text-(--btn-fg-h,inherit) enabled:hover:bg-(--btn-bg-h,transparent) enabled:hover:border-(--btn-border-h,transparent) enabled:active:text-(--btn-fg-a,inherit) enabled:active:bg-(--btn-bg-a,transparent) enabled:active:border-(--btn-border-a,transparent)"

function customVars(custom: CustomColors): Record<string, string | undefined> {
  const n = custom.normal ?? {}
  const h = { ...n, ...custom.hover }
  const a = { ...n, ...custom.active }
  return {
    "--btn-fg": n.foreground,
    "--btn-bg": n.background,
    "--btn-border": n.border,
    "--btn-fg-h": h.foreground,
    "--btn-bg-h": h.background,
    "--btn-border-h": h.border,
    "--btn-fg-a": a.foreground,
    "--btn-bg-a": a.background,
    "--btn-border-a": a.border,
  }
}

/* Base UI allows a state-callback `style`; Motion's style prop doesn't,
   so the port narrows it to a plain object. The omitted DOM handlers are
   names Motion claims for its own animation/drag callbacks. */
type ButtonProps = Omit<
  ButtonPrimitive.Props,
  "style" | "onAnimationStart" | "onDrag" | "onDragStart" | "onDragEnd"
> &
  VariantProps<typeof buttonVariants> & {
    style?: React.CSSProperties
    leadingIcon?: React.ElementType
    trailingIcon?: React.ElementType
    loading?: boolean
    custom?: CustomColors
  }

function Button({
  className,
  variant,
  size,
  shape,
  press,
  hover,
  leadingIcon: LeadingIcon,
  trailingIcon: TrailingIcon,
  loading = false,
  custom,
  disabled,
  style,
  children,
  ...props
}: ButtonProps) {
  const v = variant ?? "default"
  const interactive = !disabled && !loading
  const grow = hover === "grow" && v !== "outline" && v !== "ghost"
  const elevate = hover === "elevate"
  const pressScale =
    press === "shrink" ? 0.98 : press === "bounce" ? 0.93 : undefined

  const whileHover =
    interactive && (grow || elevate)
      ? {
          ...(grow && { scale: 1.02 }),
          ...(elevate && { y: -1, boxShadow: ELEVATE_SHADOW }),
        }
      : undefined
  const whileTap =
    interactive && (pressScale || elevate)
      ? {
          ...(pressScale && { scale: pressScale }),
          ...(elevate && { y: 0, boxShadow: ELEVATE_SHADOW_NONE }),
        }
      : undefined

  return (
    <MotionButton
      data-slot="button"
      data-loading={loading || undefined}
      disabled={disabled || loading}
      className={cn(
        buttonVariants({ variant, size, shape, press, hover }),
        custom && customClasses,
        className
      )}
      style={custom ? { ...customVars(custom), ...style } : style}
      whileHover={whileHover}
      whileTap={whileTap}
      transition={SPRING}
      {...props}
    >
      {/* Loading shows the spinner only (label + icons hidden). Fix the width
          at the call site (e.g. min-w-24) if the swap shouldn't reflow. Icon
          spans carry data-icon so the size padding tightens; `contents` keeps
          gap/centering on the button's own flexbox. */}
      {loading ? (
        <Spinner />
      ) : (
        <>
          {LeadingIcon ? (
            <span data-icon="inline-start" className="contents">
              <LeadingIcon />
            </span>
          ) : null}
          {children}
          {TrailingIcon ? (
            <span data-icon="inline-end" className="contents">
              <TrailingIcon />
            </span>
          ) : null}
        </>
      )}
    </MotionButton>
  )
}

export { Button, buttonVariants, type ButtonProps }
